### ISSUE TITLE
Node 13 support

### ISSUE THREAD

**Issue by Slessi** [jaydenseric/graphql-upload#170] opened 2019-11-22 18:01 UTC
When using this library with Node 13, I receive the following:

```
uncaughtException: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at ReadStream.deprecated [as open] (internal/util.js:55:22)
    at ReadStream.open (/project/node_modules/fs-capacitor/lib/index.js:90:11)
    at _openReadFs (internal/fs/streams.js:123:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:116:3)
    at ReadStream.deprecated [as open] (internal/util.js:70:15)
    at ReadStream.open (/project/node_modules/fs-capacitor/lib/index.js:90:11)
    at _openReadFs (internal/fs/streams.js:123:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:116:3)
    at ReadStream.deprecated [as open] (internal/util.js:70:15)
    at ReadStream.open (/project/node_modules/fs-capacitor/lib/index.js:90:11)
(node:55196) [DEP0135] DeprecationWarning: ReadStream.prototype.open() is deprecated
```

This is an issue with `fs-capacitor` https://github.com/mike-marcacci/fs-capacitor/issues/15 which has been fixed in `3.0.0` so need a version bump on this package

I can resolve this temporarily with this in my package.json

```json
    "resolutions": {
        "fs-capacitor": "3.0.0"
    }
```

There is now `fs-capacitor` `5.0.0` as well but haven't tried it

**Comment by mike-marcacci** [comment] 2019-11-22 18:21
Hi @Slessi - you're correct, adding that resolution should work for the time being. We've already made the changes to incorporate `fs-capacitor` version 4, and will be releasing that shortly. Version 5 is identical to 4 from an API standpoint but without bringing in its own stream library to support node version 8. We'll upgrade to version 5 once we can drop support for node 8 (in January, when its LTS expires).

Closing this as it's already fixed in master.

**Closed by mike-marcacci** 2019-11-22 18:21 UTC

**Comment by Slessi** [comment] 2019-11-22 18:54
@mike-marcacci nice. You have a plan when that would be release? I'm using apollo and would need to file an issue there also if they don't update

**Comment by mike-marcacci** [comment] 2019-11-22 19:05
I believe we'll have a new release after #169 gets finished. Node 12 and 13 changed the way commonjs and es modules work, and removed the mechanism for publishing both in the same library... so this is re-tooling to drop our experimental mjs support.

**Comment by gregory** [comment] 2019-12-02 21:12
Looks like graphql-upload needs to cut a new release since [fs-capacitor was bumped to 4.0.0](https://github.com/jaydenseric/graphql-upload/blame/master/package.json#L43). 
Am i missing something @mike-marcacci  @jaydenseric ?

**Comment by jaydenseric** [comment] 2019-12-02 23:01
@gregory after dogfooding what was on `master` branch the other day, it came to light that the warnings due to new `fs-capacitor` behavior need some polish. @mike-marcacci  and I have been having discussions about the best way to handle `SIGINT`, `SIGTERM` and `SIGHUP` listeners:

<img width="795" alt="Screen Shot 2019-11-29 at 2 23 58 pm" src="https://user-images.githubusercontent.com/1754873/70002055-1393bd00-15b3-11ea-81de-1245759377a8.png">

The conclusion so far is that they need to be handled by the consumer in their app (not in `graphql-upload`), and only if necessary. The documentation needs to be updated accordingly, and the examples should probably be updated so people know how to do it. With better documentation we may be able to remove the console warnings from `fs-capactitor` (in a v4 patch release?).

Mike is taking point on this, and he has been travelling in the last day but we're hoping to make some progress soon.

**Comment by gregory** [comment] 2019-12-03 04:34
Thanks for the update! 
Would be nice to update the readme to tell everyone this is only working with node <=10.x for now.

**Comment by jaydenseric** [comment] 2019-12-03 08:31
[`graphql-upload` v9.0.0](https://github.com/jaydenseric/graphql-upload/releases/tag/v9.0.0) has been published, shipping support for Node.js v13 🚀

**Comment by lcswillems** [comment] 2019-12-06 18:36
The version of `graphql-upload` in Apollo Server has not been upgraded to 9.0.0. I can't use it on Node.JS 13.

Changing the resolutions doesn't work for me.

Any solution?

**Comment by gregory** [comment] 2019-12-06 22:22
> The version of `graphql-upload` in Apollo Server has not been upgraded to 9.0.0. I can't use it on Node.JS 13.
> 
> Changing the resolutions doesn't work for me.
> 
> Any solution?

You can force it by either using the yarn's resolution or there is a npm package for npm. 

I added this in my package.json: 
```json
  "resolutions": {
    "**/**/fs-capacitor":"^5.0.0",
    "**/graphql-upload": "^9.0.0"
  }
```

**Comment by lcswillems** [comment] 2019-12-06 23:08
Thank you for your answer! I raged-quit and downgraded to Node 12...

**Comment by danieldunderfelt** [comment] 2019-12-17 06:17
I can confirm that the solution by @gregory works with Apollo Server Express.

**Comment by cesargdm** [comment] 2020-05-24 17:27
Also getting this issue using Node `14.3.0`

**Comment by gengjiawen** [comment] 2020-06-10 11:23
This worked for me when I am on Node.js 14
```
  "resolutions": {
    "**/**/fs-capacitor":"^6.2.0",
    "**/graphql-upload": "^11.0.0"
  },
```

**Comment by sapkra** [comment] 2020-06-11 13:57
I was able to remove the `fs-capacitor` resolution since v11. But maybe it's not working for everyone.

**Comment by olso** [comment] 2020-07-29 21:08
Works for `node -v` `v13.14.0`

```json
"apollo-server-koa/apollo-server-core/fs-capacitor": "^6.2.0",
"apollo-server-koa/apollo-server-core/graphql-upload": "^11.0.0"
```

**Comment by Oliver-ke** [comment] 2020-09-17 09:51
> This worked for me when I am on Node.js 14
> 
> ```
>   "resolutions": {
>     "**/**/fs-capacitor":"^6.2.0",
>     "**/graphql-upload": "^11.0.0"
>   },
> ```

I'm facing the same issue, how did you get this to work,
I added your solution to `package.json`
reinstalled packages, and yet it didn't work. currently using `node 14.1.0`

**Comment by anthager** [comment] 2020-09-21 08:11
> I'm facing the same issue, how did you get this to work,
> I added your solution to `package.json`
> reinstalled packages, and yet it didn't work. currently using `node 14.1.0`

Did you add those exact versions to you dependencies as well? I did, added the resolutions in package.json and works for me using node 14.11.0

**Comment by eyal-elkevity** [comment] 2020-09-26 13:06
hey @anthager I have the same situation, with Node v14.4, npm installed the specific versions of graphql-upload and fs-capacitor like @Oliver-ke did and it doesn't work... :( did just the dependencies, just the resolutions entry, both together, nada :( :(

**Comment by eden** [comment] 2020-10-13 18:39
For anyone still hitting this, the resolutions seems to work correctly without globbing. For example:

```
  "resolutions": {
    "fs-capacitor":"^6.2.0",
    "graphql-upload": "^11.0.0"
  }
```

Also make sure you include the preinstall script: `npx npm-force-resolutions`

**Comment by sannge** [comment] 2020-10-21 18:06
> For anyone still hitting this, the resolutions seems to work correctly without globbing. For example:
> 
> ```
>   "resolutions": {
>     "fs-capacitor":"^6.2.0",
>     "graphql-upload": "^11.0.0"
>   }
> ```
> 
> Also make sure you include the preinstall script: `npx npm-force-resolutions`

I cannot thank you enough, it suddenly works like a miracle!

**Comment by sahanjith** [comment] 2020-11-18 18:44
> For anyone still hitting this, the resolutions seems to work correctly without globbing. For example:
> 
> ```
>   "resolutions": {
>     "fs-capacitor":"^6.2.0",
>     "graphql-upload": "^11.0.0"
>   }
> ```
> 
> Also make sure you include the preinstall script: `npx npm-force-resolutions`

Thank you! This worked for me with Node v14.15.0.

**Comment by mohamed-abdelrhman** [comment] 2021-01-11 19:17
> For anyone still hitting this, the resolutions seems to work correctly without globbing. For example:
> 
> ```
>   "resolutions": {
>     "fs-capacitor":"^6.2.0",
>     "graphql-upload": "^11.0.0"
>   }
> ```
> 
> Also make sure you include the preinstall script: `npx npm-force-resolutions`

I can confirm this works for node 14

**Comment by ethanwilkins** [comment] 2021-01-18 17:58
I'm using node 14.13.1 with Next.js and apollo-server-micro. The following resolved the issue:
```
"resolutions": {
    "fs-capacitor": "^6.2.0"
  }
```

**Comment by melodyLeonard** [comment] 2021-03-18 10:32
> For anyone still hitting this, the resolutions seems to work correctly without globbing. For example:
> 
> ```
>   "resolutions": {
>     "fs-capacitor":"^6.2.0",
>     "graphql-upload": "^11.0.0"
>   }
> ```
> 
> Also make sure you include the preinstall script: `npx npm-force-resolutions`

I am uding yarn package manager and while trying to include this, I get an error that package.lock.json is not found. Do I need to switch to npm or is there a way to do this for yarn

**Comment by XshubhamX** [comment] 2021-04-08 17:00
const id = shortid.generate();
  const { createReadStream, filename } = await file;
  await imageExtensionCheck(filename);
  // upload new image
  let stream = createReadStream();
  await new Promise((res) =>
    stream
      .on('open', () =>
        stream.pipe(
          createWriteStream(
            path.join(__dirname, '../images', `/${id}-${filename}`)
          )
        )
      )
      .on('close', res)
  );

error is:-DeprecationWarning: ReadStream.prototype.open() is deprecated

can anyone tell what i am doing wrong

**Comment by jaydenseric** [comment] 2021-04-08 23:26
@XshubhamX you truly are shameless. ***Yesterday*** you agreed not to spam poorly formatted comments asking for help with your work:

https://github.com/jaydenseric/graphql-upload/issues/125#issuecomment-815366424

**Comment by XshubhamX** [comment] 2021-04-09 03:48
hey you are here to help ,or you want to teach moral science .If you dont want to help then leave

**Comment by evertoncastro** [comment] 2021-04-13 22:04
Worked for me in node **14.16.1** with the following configuration:

```
"resolutions": {
    "fs-capacitor": "^6.2.0",
    "graphql-upload": "^11.0.0"
}
```

I needed to add force-resolutions inside "scripts"

```
"scripts": {
    ....
    "preinstall": "npx npm-force-resolutions"
}

```

Remove ./node_modules and install dependencies again.

**Comment by ezalivadnyi** [comment] 2021-04-23 09:22
> Worked for me in node **14.16.1** with the following configuration:
> 
> ```
> "resolutions": {
>     "fs-capacitor": "^6.2.0",
>     "graphql-upload": "^11.0.0"
> }
> ```
> 
> I needed to add force-resolutions inside "scripts"
> 
> ```
> "scripts": {
>     ....
>     "preinstall": "npx npm-force-resolutions"
> }
> ```
> 
> Remove ./node_modules and install dependencies again.

Hi! Thanks! This solution works with **yarn**, but doesn't work with **npm install**.
**node -v:** v14.15.4
**npm -v:** 6.14.10

**Comment by jaydenseric** [comment] 2021-04-23 09:32
@ezalivadnyi don’t try to work with the outdated Apollo Server file upload implementation; disable it using `uploads: false` and install the latest version of `graphql-upload` from scratch, following the [setup instructions](https://github.com/jaydenseric/graphql-upload#setup) in the readme.

https://github.com/jaydenseric/apollo-upload-examples/blob/be1444a0aa8768c6fe2e2c96119eb2b6344fcc50/api/server.js#L78-L81

This won't be a waste of effort because Apollo plans to never update the version of `graphql-upload` they use in Apollo Server; eventually in Apollo Server v3 they will remove the built in file uploads support in favor of users setting it up themself anyway.

**Comment by vincentdesmares** [comment] 2022-03-18 10:35
I used the solution from Schnitzel and it worked perfectly. See : https://github.com/uselagoon/lagoon/pull/2747
