### ISSUE TITLE
Wrong documentation or miss understanding ?

### ISSUE THREAD

**Issue by pedromdantunes** [jaydenseric/graphql-upload#285] opened 2021-12-03 15:34 UTC
Hi!
I was reading your documentation and there, you show that FileUpload interface is an interface with: 
- filename: string;
- mimetype: string;
- encoding: string;
- createReadStream: FileUploadCreateReadStream
However, on index.d.ts, you show that interface FileUpload consists of:
- filename: string;
- mimetype: string;
- encoding: string;
- createReadStream(): ReadStream

So, what happens ? When I try to do a stream like `const stream = file.createReadStream()`, I have an exception like "file.createReadStream is not a function".

package.json
graphql-upload@^13.0.0
@types/graphql-upload@^8.0.7

**Comment by jaydenseric** [comment] 2021-12-05 23:27
What the `Upload` scalar promise resolves is fully documented in the readme:

https://github.com/jaydenseric/graphql-upload/tree/v13.0.0#type-fileupload

> However, on index.d.ts, you show that interface FileUpload consists of:

I don't show that; the `@types/graphql-upload` package is not maintained by me. Feel free to PR Definitely Typed to update those types if any are wrong.

> I have an exception like "file.createReadStream is not a function".

Do you have a runtime exception, or are you talking about a TypeScript type check error message?

**Comment by pedromdantunes** [comment] 2021-12-06 11:11
> I don't show that; the @types/graphql-upload package is not maintained by me. Feel free to PR Definitely Typed to update those types if any are wrong.
Yeah, you're right, my bad...

> Do you have a runtime exception, or are you talking about a TypeScript type check error message?
Both

**Comment by jaydenseric** [comment] 2021-12-06 11:12
If you run `npm ls graphql-upload` within your project, do you see multiple versions of `graphql-upload` installed?

**Comment by pedromdantunes** [comment] 2021-12-06 11:15
Nop, only graphql-upload@13.0.0

**Comment by jaydenseric** [comment] 2021-12-06 11:17
If you `console.log` what the awaited `Upload` scalar promise resolves in the resolvers, what do you see?

**Comment by pedromdantunes** [comment] 2021-12-06 11:21
https://gyazo.com/1c47e1ca057f38ca33d8318e1680ac4a

**Comment by pedromdantunes** [comment] 2021-12-06 11:22
![image](https://user-images.githubusercontent.com/56557618/144837562-bfc1648e-a61e-428e-980a-cbad40fbed29.png)

**Comment by jaydenseric** [comment] 2021-12-06 11:23
It looks like it is working… you're supposed to await the upload, then you can do `.createReadStream()` on what it resolves.

**Comment by pedromdantunes** [comment] 2021-12-06 11:25
Yeah, but when I try to do `.createReadStream()`, triggers the exception `file.createReadStream is not a function`

**Comment by jaydenseric** [comment] 2021-12-06 11:38
That is really strange. Maybe you are not using the `GraphQLUpload` scalar exported from `graphql-upload`, but another one?

If you reach into `node_modules`, and put a `console.log` just before these lines, do both log when you run into the problem?

- https://github.com/jaydenseric/graphql-upload/blob/0cbc9d90a181ace59be279fee4c3b269c47d1cbe/public/processRequest.js#L278
- https://github.com/jaydenseric/graphql-upload/blob/0cbc9d90a181ace59be279fee4c3b269c47d1cbe/public/GraphQLUpload.js#L81

**Comment by pedromdantunes** [comment] 2021-12-06 12:06
Yes, I can `console.log` both lines, 278 and 81

**Comment by jaydenseric** [comment] 2021-12-06 12:40
I just updated the example API to use the latest `graphql` and `graphql-upload` versions, and everything works fine:

https://github.com/jaydenseric/apollo-upload-examples/tree/master/api

There is something funky going on in your project.

**Comment by jaydenseric** [comment] 2021-12-06 12:46
Closing because this problem couldn't be reproduced, so there is nothing I can action from here. If you manage to put together a minimal project (vanilla Node.js, no TypeScript or other build tools) that demonstrates a specific bug in this `graphql-upload` package we can reopen and investigate further.

**Closed by jaydenseric** 2021-12-06 12:46 UTC
Labels: question

**Comment by pedromdantunes** [comment] 2021-12-06 12:49
Ok, thanks for the help, I will try do my best to replicate this.
I'm using this with nestjs, I don't know if it is the problem or not... But, no problem, I will figure this out.

Thanks a lot!
