### ISSUE TITLE
Error: A ReadStream cannot be created from a destroyed WriteStream.

### ISSUE THREAD

**Issue by mrceperka** [jaydenseric/graphql-upload#208] opened 2020-05-24 21:30 UTC
Hi,
I've got problem with reading contents from stream.

Either I get this error (:point_down:) or writeStream hangs forever...
```
Error: A ReadStream cannot be created from a destroyed WriteStream.
    at WriteStream.createReadStream (/var/bb/node_modules/fs-capacitor/dist/index.js:174:19)
    at Object.createReadStream (/var/bb/node_modules/graphql-upload/lib/processRequest.js:297:28)
```

Example code:
```ts
class ImageStorageService {
  async uploadImage(upload: FileUpload): Promise<string> {
    const filename = `${cuid()}-${upload.filename}`;
    const tempFile = `${tmpdir()}/${filename}`;
    const readStream = upload.createReadStream();

    const writeStream = createWriteStream(tempFile);
    readStream.pipe(writeStream);

    // hangs forever, no finish event emitted
    const writePromise = new Promise((res) => {
      writeStream.on("open", () => {
        console.log("Stream opened");
      });
      writeStream.on("ready", () => {
        console.log("Stream ready");
      });
      writeStream.on("finish", () => {
        console.log("Stream finished");
        res();
      });
    });
    await writePromise;
   // ...
  }
}
```

Any ideas? Am I doing something wrong with streams?

Btw I had to use this fix to prevent `maximum call stack size exceeded` error.
```
  "resolutions": {
    "**/**/fs-capacitor": "^5.0.0",
    "**/graphql-upload": "^10.0.0"
  }
```
Node: **v14.2.0**

**Comment by mrceperka** [comment] 2020-05-24 21:42
Probably works with Node: **v12.16.1**

**Comment by mike-marcacci** [comment] 2020-05-28 01:35
I suspect this is behaving correctly and that your `uploadImage` function is likely being called _after_ all your resolvers have returned.

Once the GraphQL operation has completed, the files backing these streams are flagged for deletion, and new read streams cannot be created from them. They will continue to serve existing read streams, though.

Essentially, it's expected that you create all necessary streams before your resolver returns/resolves.

**Comment by mike-marcacci** [comment] 2020-05-28 01:36
I'm going to go ahead and close this issue, because this is expected behavior, but feel free to continue asking here if you need further clarification.

**Comment by mike-marcacci** [comment] 2020-05-28 01:39
Actually... the fact that you say it works in node 12 makes me curious if there is something else going on as well. I suspect that it's simply differences in the order of events being emitted from node's stream library, but I want to make sure, so I'm reopening.

@mrceperka can you share the resolver code that calls this?

**Comment by mrceperka** [comment] 2020-05-28 07:08
Hi, will share later today. Thanks for your interest

**Comment by mrceperka** [comment] 2020-05-28 07:39
I am using nestjs, and `@nestsjs/graphql` package.
Also, node:12-alpine docker image.

```typescript
// tournament.resolver.ts

@Resolver((of) => Tournament)
@UseGuards(GqlAuthGuard)
export class TournamentResolver {
  constructor(
    private tournamentService: TournamentService,
    private imageStorage: ImageStorageService,
    private prisma: PrismaService
  ) {}

  @Mutation((returns) => Tournament)
  @UseGuards(new GqlRolesGuard([Role.ADMIN]))
  async createTournament(
    @UserEntity() user: User,
    @Args("data") dto: CreateTournamentInput
  ) {
    if (dto.mainMediaUpload) {
      const { url, filename } = await this.imageStorage.uploadPublic(
        await dto.mainMediaUpload
      );
      dto.mainMediaUpload = undefined;
      dto.mainMediaUrl = url;
      dto.mainMediaFilename = filename;
    }

    return this.tournamentService.createTournament(user.id, dto);
  }
}

```

```ts
// imagestorage.service.ts

@Injectable()
export class ImageStorageService {
  constructor(private firebaseStorage: FirebaseStorageService) {}

  async uploadPublic(
    upload: FileUpload
  ): Promise<{ url: string; filename: string }> {
    const filename = `${cuid()}-${upload.filename}`;
    const tempFile = `${tmpdir()}/${filename}`;
    const readStream = upload.createReadStream();

    const writeStream = createWriteStream(tempFile);
    readStream.pipe(writeStream);

    const writePromise = new Promise((res) => {
      writeStream.on("finish", () => {
        res();
      });
    });
    await writePromise;

    const ref = await this.firebaseStorage.storage
      .bucket()
      .upload(tempFile, { destination: filename, public: true });

    return {
      url: ref[1].mediaLink,
      filename,
    };
  }
}
```

**Comment by koresar** [comment] 2020-06-04 04:38
I'm not sure, but looks like the `writePromise` is redundant. Also, the `tempFile` is redundant.

I would presume this would work (I have never dealt with Firebase though):
```js
    const readStream = upload.createReadStream();
    const writeStream = this.firebaseStorage.storage
      .bucket()
      .file(`${cuid()}-${upload.filename}`)
      .createWriteStream({ public: true });

    await require("promisified-pipe")(readStream, writeStream);

    return {
//      url: ref[1].mediaLink, // Don't know how to get this one 
      filename,
    };
```

**Comment by mrceperka** [comment] 2020-06-04 06:34
@koresar Well if you use another package, you make it rendundant. `tempFile` might be redundat... but firebase `.file()` requires a path an existing file that will be uploaded.

None of things mentioned above should have impact on the error _(Error: A ReadStream cannot be created from a destroyed WriteStream.)_

**Comment by koresar** [comment] 2020-06-04 09:20
I think you're wrong. The `.file()` requires a path within the Firebase store, not the existing file on your filesystem. [Docs](https://googleapis.dev/nodejs/storage/latest/Bucket.html#file):

![image](https://user-images.githubusercontent.com/1622575/83738671-f0e47d00-a697-11ea-93a4-cceb4e4d823d.png)

I might got the code wrong. However, what I found in the internets is that `.upload()` is a wrapper around `.createWriteStream()`. In other words - you need to pipe that `readStream` to the result from the `.createWriteStream()`. I just don't know the right arguments.

Regarding your error. I've published this module today: https://github.com/koresar/graphql-upload-minimal
It avoids `fs-capacitor` by doing other tradeoffs. It should be a drop-in replacement for the `graphql-upload`. It might work. Try it.

**Comment by mrceperka** [comment] 2020-06-04 10:19
@koresar Damn you are right, I was using `upload()` instead of `file()`. Apologies for any confusion. Will definitely try it. Thanks :pray:

**Comment by jaydenseric** [comment] 2020-06-08 15:01
Hope you figured it out ok; we can reopen this issue if a specific `graphql-upload` bug is discovered.

**Closed by jaydenseric** 2020-06-08 15:01 UTC

**Comment by JaffParker** [comment] 2020-07-29 16:42
I'm not sure what this error is caused by, but this is the only issue I've found with it, so I assume it's `graphql-upload`. Here's my code:

```ts
// file-uploads.resolver.ts

@ArgsType()
class UploadFileArgs {
  @Field(() => [GqlUpload]) files: Array<Promise<FileUpload>>
}

@Resolver(() => File)
export class FileUploadsResolver {
  constructor(private uploads: FileUploadsService) {}

  @Mutation(() => [File])
  @UseGuards(SignedInGuard)
  async uploadFiles(
    @Args() { files: filePromises }: UploadFileArgs,
  ): Promise<File[]> {
    const returns: File[] = []

    for (const filePromise of filePromises) {
      const { createReadStream, ...file } = await filePromise
      returns.push(await this.uploads.uploadAndRecord(file, createReadStream()))
    }

    return returns
  }
}
```

```ts
// file-uploads.service.ts

interface UploadInput {
  filename: string
  mimetype: string
  encoding: string
}

@Injectable()
export class FileUploadsService {
  constructor(
    @InjectRepository(File)
    private uploadRepo: Repository<File>,
    private config: ConfigService,
  ) {}

  async uploadAndRecord(file: UploadInput, readStream: Stream): Promise<File> {
    const fileUpload = await this.uploadRepo.save(
      this.uploadRepo.create({
        name: file.filename,
        mimetype: file.mimetype,
      }),
    )

    try {
      this.writeStreamIntoFile(readStream, fileUpload)

      return fileUpload
    } catch (error) {
      this.uploadRepo.delete(fileUpload)
      throw error
    }
  }

  resolveFileName(upload: File): string {
    return resolve(
      this.config.get('uploads.dir'),
      `${upload.id}.${extension(upload.mimetype)}`,
    )
  }

  private async writeStreamIntoFile(
    stream: Stream,
    uploadInfo: File,
  ): Promise<void> {
    const writeFileStream = createWriteStream(this.resolveFileName(uploadInfo))

    stream.pipe(writeFileStream).on('error', (error: Error) => {
      writeFileStream.close()

      if (error instanceof MimeNotAllowedError)
        throw new InputError(UploadErrors.FileTypeNotAllowed)
    })
  }
}

```

Interestingly, it all used to work up until this morning. But while debugging this, I've also found that it's been butchering all uploaded PDF's (images were fine). I don't know if that is an issue with graphql-upload or not though...

**Comment by jaydenseric** [comment] 2020-07-29 23:20
@JaffParker I haven't looked at all your code with respect to your issue, but this is not good:

```js
    for (const filePromise of filePromises) {
      const { createReadStream, ...file } = await filePromise
      returns.push(await this.uploads.uploadAndRecord(file, createReadStream()))
    }
```

That is awaiting the file promises one after the other, in order. It's better to process them all in parallel — at that point in the code there is no guarantee the files will stream in ordered the way you expect.

See ***Tips***:

> - Process multiple uploads asynchronously with [`Promise.all`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/promise/all) or a more flexible solution such as [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) where an error in one does not reject them all.
>
> — https://github.com/jaydenseric/graphql-upload#tips

**Comment by JaffParker** [comment] 2020-07-30 01:02
@jaydenseric that's actually what it was initially, and that was the state in which in broke. I mean, concurrent or not, it's not supposed to unload the file until the resolver is done, but it doesn't seem to be the case.

Update: my colleague noticed in our package-lock.json that `fs-capacitor` for some reason got downgraded from version 5.0.0 to version 2.0.4. We're not sure why that happened, possibly another package required a lower version. Is it possible that it's the cause?

**Comment by koresar** [comment] 2020-07-30 01:57
Hey, @JaffParker 

Few messages above I mentioned that we've forked `graphql-upload`.
It's main purpose of the fork - drop the `fs-capacitor`. See differences: https://www.npmjs.com/package/graphql-upload-minimal#differences-to-graphql-upload

If you do not reference the same file more than once in your GraphQL query (99% of the cases I believe), then `graphql-upload-minimal` should be a drop in replacement for you.

PS: Sorry @jaydenseric for promoting myself here. I just strongly believe that my suggestion would help Jaff.

**Comment by jaydenseric** [comment] 2020-07-30 03:20
@JaffParker Be sure you are using the latest `graphql-upload` and `fs-capacitor` versions in `node_modules` (use `npm ls graphql-upload`, `npm ls fs-capacitor`), and be sure that there are not multiple versions in use. Fixing that will solve a lot of problems. And don't deliberately write incorrect code; it's better to solve the original problem than create new ones 😅

**Comment by JaffParker** [comment] 2020-07-30 03:36
@jaydenseric thanks for the advice, I'll try upgrading. The graphql-upload version is at the latest though, but I'll try upgrading fs-capacitor

No need to emphasize the incorrect code though. It's not incorrect as it should still be functional, just slower, and like I said, it actually was something like this:

```ts
// ... Resolver code

return await Promise.all(files.map(file => this.filesService.upload(file)))
```

I was just trying different solutions and that's the code I ended up with at the time of posting. Again, if graphql-upload is supposed to break if I don't upload files concurrently, it doesn't seem right.

**Comment by jaydenseric** [comment] 2020-07-30 03:46
> if graphql-upload is supposed to break if I don't upload files concurrently, it doesn't seem right.

`graphql-upload` absolutely can handle the files uploaded in any order, that's the point. Your resolver code needs to account for that by not hardcoding what is expected to arrive first. For example:

```js
const variables = {
  a: fileB, // First file to stream into the server.
  b: [
    fileA, // Second file to stream into the server.
    fileB, // First file to stream into the server.
  ],
};
```

For variable `b` would not be good to await `fileA` before processing `fileB`.

**Comment by aseerkt** [comment] 2020-12-09 04:43
I am having trouble getting my code to work.
`@Mutation(() => PostResponse)
  @UseMiddleware(isAuth)
  async addPost(
    @Arg('caption') caption: string,
    @Arg('image', () => GraphQLUpload)
    file: FileUpload,
    @Ctx() { req }: MyContext
  ): Promise<PostResponse> {
    const { filename, createReadStream } = file;
    console.log('Hero goes file', file);
    const uploadTime = new Date().toISOString();
    const stream = createReadStream();
    const uploadPath = path.join(
      __dirname,
      `../../images/${uploadTime}_${filename}`
    );

    const isUploaded: boolean = await new Promise((resolve, reject) =>
      stream
        .pipe(createWriteStream(uploadPath))
        .on('error', (err) => {
          console.log('on Error', err);
          reject(false);
        })
// onFinish block does not seems to work
        .on('finish', () => {
          console.log('onFinish');
          unlink(uploadPath, () => {
            resolve(true);
          });
        })
    );
    const imgURL = `${req.headers.host}/images/${uploadTime}_${filename}`;
    const savePost = async () => {
      const user = await User.findOne({ id: req.session.userId });
      const post = Post.create({
        caption,
        imgURL,
        user,
      });
      await post.save();
      return post;
    };
    if (isUploaded) {
      try {
        return { post: await savePost() };
      } catch (err) {
        return { error: 'Post save failed' };
      }
    } else {
      return { error: 'Upload Failed' };
    }
  }`

File is uploaded fine. But rest of the operations are not working. I am really new to GraphQL world. A help will be appreciated

**Comment by mike-marcacci** [comment] 2020-12-09 05:25
@aseerkt in your example, `stream` is a [readable stream](https://nodejs.org/api/stream.html#stream_readable_streams), which is being piped into the [writable stream](https://nodejs.org/api/stream.html#stream_writable_streams) returned by your call to `createWriteStream(uploadPath)`. The [`finish` event](https://nodejs.org/api/stream.html#stream_event_finish) is something that is emitted by the latter, but you are listening for it on the former.

**Comment by aseerkt** [comment] 2020-12-11 11:05
@mike-marcacci Sorry for bothering you. But now I strangely have two versions of fs-capacitor
```bash
$ npm ls fs-capacitor
->  fs-capacitor@5.0.1  extraneous
     UNMET DEPENDENCY fs-capacitor@^6.1.0
```
Which version of fs-capacitor should I add to `resolutions`.

**Comment by mike-marcacci** [comment] 2020-12-11 18:30
Hmm, that would depend on _why_ you have two versions. Usually `extraneous` means you have something a bit strange going on. You probably need to look at your dependency graph a bit closer. That said [here is the release for v6](https://github.com/mike-marcacci/fs-capacitor/releases/tag/v6.0.0) so you can make a call on whether or not there is a compatibility issue with your code.

**Comment by koresar** [comment] 2020-12-12 09:32
Yeah. That capacitor caused me same troubles. That's one of the reasons I
created and maintain this fork:
https://github.com/flash-oss/graphql-upload-minimal

It's a drop in replacement for graphql-upload (for most use cases). Just
without this capacitor and few other dependencies. Hence the word
"minimal". Also, the README shows few more (simplified) examples.

Try it
