### ISSUE TITLE
`parseValue` expects get an instance of `Upload` value

### ISSUE THREAD

**Issue by ARHariri** [jaydenseric/graphql-upload#197] opened 2020-04-27 11:52 UTC
Hi there.
I cannot upload a file as I get "Upload value invalid" error, unless I override `parseValue` function. As I see, there is a [condition](https://github.com/jaydenseric/graphql-upload/blob/73ef939ef16a40358eb80e0a54c5c3ead725b2fe/lib/GraphQLUpload.js#L65) in `parseValue` function (in the `GraphQLUpload.js` file) that expects to get an instance of [`Upload`](https://github.com/jaydenseric/graphql-upload/blob/73ef939ef16a40358eb80e0a54c5c3ead725b2fe/lib/Upload.js#L14) `value`.
I think this condition should be changed to something like this `value instanceof Blob` to resolve the error (Check the `value` to be an instance of Blob instead of `Upload`).

p.s.: It seems this condition added to resolve [this issue](https://github.com/jaydenseric/graphql-upload/issues/175).

**Comment by jaydenseric** [comment] 2020-04-27 11:57
Why would you expect it to not be an `Upload` instance? Perhaps you are importing the `GraphQLUpload` scalar from a different `graphql-upload` version than the `processRequest` function is from. You can check by running `npm ls graphql-upload` - there should only be one version in your `node_modules`.

**Comment by ARHariri** [comment] 2020-04-27 12:46
I use `apollo-server-express` that uses `graphql-upload` v8.1.0 as a dependency and I installed the latest version (v10.0.0) to define `Upload` scalar (`apollo-server` handles uploading files (with `graphql-upload`) but I should create `Upload` scalar manually because I use `nexus` to create GraphQL schemas). So there are two versions of `graphql-upload` package inevitably.

**Comment by jaydenseric** [comment] 2020-04-27 12:54
Closing because the problem is not an issue with `graphql-upload`. There are existing issues you can find in the Apollo repos about `graphql-upload` being outdated in their dependencies, and the various workarounds available to manually upgrade.

**Closed by jaydenseric** 2020-04-27 12:54 UTC
