### ISSUE TITLE
Forwarding upload to another service times out (ECONNRESET)

### ISSUE THREAD

**Issue by sevetseh28** [jaydenseric/graphql-upload#259] opened 2021-09-08 10:35 UTC
Hi! I have a webserver acting as a gateway using NestJS and I successfully implemented a Mutation accepting a file with this package (graphql-upload).

The problem I'm currently having is that after accepting the file upload I wanna reupload that file to another service by doing the following HTTP call:
```typescript
async uploadImage(
    userId: string,
    uploadData: ImageUploadArg,
  ): Promise<{ id: string }> {
    const imgFileUpload: FileUpload = await uploadData.imageFile;
    let data = new FormData();
    data.append('prefix', uploadData.prefix);
    data.append('category', uploadData.category);
    const readStream = imgFileUpload.createReadStream();
    data.append('image', readStream, imgFileUpload.filename);
    return this.httpService
      .post(
        `${this.configService.get('anotherServiceURL')}/${userId}/images`,
        data,
        {
          headers: {
            ...data.getHeaders()
          },
          maxBodyLength: Infinity,
          maxContentLength: Infinity,
        },
      )
      .toPromise()
      .then((res) => {
        return res.data;
      })
  }
```

Problem is that when calling the http service, it times out with an ECONNRESET error. I am assuming there's something wrong with the read Stream. Any ideas?

Im using 
* Node 14.15.3
* graphql-upload 12.0.0
* NestJS 8 with the in-built graphql upload disabled (therefore im using this package directly as middleware)

Thank you!

**Comment by jaydenseric** [comment] 2021-09-08 10:56
Closing because we only keep issues open here that describe a specific `graphql-upload` bug, or request a new feature. If anyone would like to assist in debugging this problem or has a suggestion, feel free to comment! Also, if you figure it out you're welcome to comment what worked in case it helps others in a similar situation.

**Closed by jaydenseric** 2021-09-08 10:56 UTC

**Comment by sevetseh28** [comment] 2021-09-08 13:30
But isnt it possible that this is an actual bug with `graphql-upload`? Why did you rule it out immediately? Knowing that might help me to debug it. Thanks!

**Comment by jaydenseric** [comment] 2021-09-09 01:05
The way open source works is you debug your own project, and find out if it's a `graphql-upload` bug. When you are sure it is, _then_ you report it here. What doesn't work, is expecting me to debug your project code (which I don't have easy access to, or a full understanding of) to find out if it's a `graphql-upload` bug, and pay me nothing when it's not.

The last `graphql-upload` bug was found in 2019, and since then the package has been installed > 83 million times. People still raise issues asking for help with their projects though. Sometimes a `graphql-upload` user is stuck on something easy for me to spot and help with and so I do, sometimes not. Either way, the issue is with the project not `graphql-upload` so it gets closed.

**Comment by sevetseh28** [comment] 2021-09-09 05:47
Wow 

> The way open source works is you debug your own project, and find out if it's a `graphql-upload` bug. When you are sure it is, _then_ you report it here. What doesn't work, is expecting me to debug your project code (which I don't have easy access to, or a full understanding of) to find out if it's a `graphql-upload` bug, and pay me nothing when it's not.
> 
> The last `graphql-upload` bug was found in 2019, and since then the package has been installed > 83 million times. People still raise issues asking for help with their projects though. Sometimes a `graphql-upload` user is stuck on something easy for me to spot and help with and so I do, sometimes not. Either way, the issue is with the project not `graphql-upload` so it gets closed.

I'm sorry Jayden but I think your attitude is not right 
at all and you are overreacting. I'm sorry if I didn't debug it enough but the way open source works is helping out the community and don't expect getting paid by doing so. I never expected you to debug it either. 

It's sad to see such a reaction and response. Anyhow, thank you.

**Comment by ivoilic** [comment] 2022-05-09 07:31
@sevetseh28 Did you ever resolve this? I'm having the same issue. I've tried many variation but it always seems to come back to something being off with the stream itself.

**Comment by jaydenseric** [comment] 2022-05-09 08:23
@ivoilic make sure that your sever (i.e. Apache or NGINX) config has limits greater than those configured for `graphql-upload`, and make sure that you are promisifying and awaiting the end of the file upload streams in resolvers.

**Comment by jaydenseric** [comment] 2024-09-12 00:01
Also, maybe take a look at https://github.com/jaydenseric/apollo-upload-client/issues/344#issuecomment-2041368669 .
