### ISSUE TITLE
Uploading file with extra payload in variables doesn't seem working

### ISSUE THREAD

**Issue by vincentwinkel** [jaydenseric/graphql-upload#331] opened 2022-08-16 07:39 UTC
After days of investigation (supertest, apollo, graphql-upload, ...) I finally could find the origin of my issue: when I upload a file, using extra payload directly in the query, it works:

<img width="702" alt="Screenshot 2022-08-15 at 15 31 43" src="https://user-images.githubusercontent.com/1402505/184823581-edf4da4a-2b70-423f-8ac6-253d0ae67078.png">

If I add the extra payload in variables, it does'nt work (I replaced here `input` from an object to a string for simplicity of debugging):

<img width="980" alt="Screenshot 2022-08-16 at 09 35 30" src="https://user-images.githubusercontent.com/1402505/184823807-d524b762-c807-46f4-b4fd-799985eb04d7.png">

Operations: `{ "query": "mutation a($file: Upload!, $input: String!) { uploadFile(file: $file, input: $input) }" }`
Map: `{ "0": ["variables.file"], "1": ["variables.input"] }`

I found a lot of examples / tuto / forum topics explaininig how to deal with supertest, like [this one](https://github.com/jaydenseric/graphql-upload/issues/125), very helpful, but then I realiseed nobody was trying to add more than 1 param (the file to upload).
Is there really a bug or I misunderstand something?
I also tried to use FormData (not compatible anymore with supertest), to inject the variables directly in `operations`, to try with postman, curl, supertest, nodejs, ...

**Comment by jaydenseric** [comment] 2022-08-16 07:44
Hi @vincentwinkel, if you paste the operations JSON in a markdown code block I can copy from I'll write the structure of a correct request for you; the problem is that the GraphQL multipart request form fields you are attempting is not according with the spec:

https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure

**Comment by vincentwinkel** [comment] 2022-08-16 07:51
My bad @jaydenseric I didnt expect an anwer so fast. I wanted to add the version used but then I realised it's out of date (v13), so I'm trying to install the last version, but get another issue aas mentionned [here](Operations: `{ "query": "mutation a($file: Upload!, $input: String!) { uploadFile(file: $file, input: $input) }" }`
Map: `{ "0": ["variables.file"], "1": ["variables.input"] }`)

**Comment by jaydenseric** [comment] 2022-08-16 08:49
Closing because this is not an issue with `graphql-upload` but a usage question about how to structure a [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec).

The numbered fields following `operations` and `map` should only be file fields, but you are incorrectly adding one for a string value. You are also missing the `variables` JSON within the `operations` field. The `variables` should contain the same stuff as a regular GraphQL post request, just with file values replaced with `null`.

**Closed by jaydenseric** 2022-08-16 08:49 UTC

**Comment by vincentwinkel** [comment] 2022-08-16 09:15
Like said above, I tried to add the `variables` directly in the `operations` field, it also didnt work, **because I kept the wrong mapping**.
Now, it indeed works. I post for the ones who are stuck as well.
<img width="752" alt="Screenshot 2022-08-16 at 11 12 09" src="https://user-images.githubusercontent.com/1402505/184843111-61319ead-98fb-4406-98e9-acbd922c7ffe.png">
Operations: `{ "query": "mutation a($file: Upload!, $input: String!) { uploadFile(file: $file, input: $input) }", "variables": { "file": true, "input": "toto" } }`
Map: `{ "0": ["variables.file"] }`

Thanks
