### ISSUE TITLE
 Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by shriram1056** [jaydenseric/graphql-upload#242] opened 2021-04-12 06:19 UTC
i apologize for creating a new issue but i have tried everything for the past few days to no avail. 

this my apollo client code
```
const httpLink = new createUploadLink({
    uri: 'http://localhost:4001/graphql',
    credentials: 'include', 
    headers: {
      cookie:
        (typeof window === 'undefined'
          ? ctx?.req?.headers.cookie
          : undefined) || '',
    },
  })

```

on the node server, i have used upload:false as per apollo docs.
```
const server = new ApolloServer({
    uploads: false
.....
})
```

this is what my resolver looks like

```
  @Mutation(() => Boolean)
  async addPicture(
    @Arg('picture', () => GraphQLUpload)
    { createReadStream, filename }: Upload
  ): Promise<boolean> {
    console.log(filename)
    return new Promise((resolve, reject) =>
      createReadStream()
        .pipe(createWriteStream(__dirname + `../images/${filename}`))
        .on('finish', () => resolve(true))
        .on('error', () => reject(false))
    )
  }
```

i am getting the following error: Error: Unexpected token P in JSON at position 0.

P.S. before marking this as closed, please look at this stackoverflow post: [https://stackoverflow.com/questions/64971480/cant-upload-files-with-apollo-client-graphql-in-next-js-app-post-body-missing](url). this post explain the problem better than i have done here

**Comment by jaydenseric** [comment] 2021-04-12 06:31
Duplicate of https://github.com/jaydenseric/graphql-upload/issues/241.

**Closed by jaydenseric** 2021-04-12 06:31 UTC
